<!DOCTYPE html>
<html lang="en">

<head>
  <title>Charter Yachts</title>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <meta name="description" content="" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
  <style>
    * {
      box-sizing: border-box;
    }

    body {
      margin: 0 auto;
    }

    h3 {
      font-size: 2vh;
    }

    a {
      color: black;
      text-decoration: none;
    }

    a:hover {
      color: black;
      text-decoration: underline;
    }

    .listings {
      list-style: none;
      flex-wrap: wrap;
      display: flex;
      padding: 0;
      margin: 0;
    }

    .listings li {
      border-bottom: 1px solid black;
      border-right: 1px solid black;
      text-align: center;
      flex: 1 0 33%;
      max-width: 33%;
      padding: 10px;
    }

    .listings li img {
      width: 100%;
    }
  </style>
</head>

<body>
  <div class="ci-search-form container-fluid">
    <form id="search" method="GET">
      <div class="row">
        <div class="col-sm-12 col-lg-2 px-1 pb-2">
          <select name="area" class="brand-border" title="Charter location">
            <option value="">Charter Location</option>
            <option value="AFRICA">Africa</option>
            <option value="ARABIAN_GULF">Arabian Gulf</option>
            <option value="CANADA">Canada</option>
            <option value="CARIBBEAN">Caribbean</option>
            <option value="CENTRAL_AMERICA">Central America</option>
            <option value="EAST_ASIA">East Asia</option>
            <option value="EAST_COAST_SOUTH_AMERICA">East Coast South America</option>
            <option value="EAST_COAST_UNITED_STATES" selected="selected">East Coast United States</option>
            <option value="EAST_MEDITERRANEAN">East Mediterranean</option>
            <option value="INDIAN_OCEAN">Indian Ocean</option>
            <option value="INDONESIA">Indonesia</option>
            <option value="NORTHERN_EUROPE">Northern Europe</option>
            <option value="OCEANIA">Oceania</option>
            <option value="RUSSIA">Russia</option>
            <option value="SOUTH_EAST_ASIA">South East Asia</option>
            <option value="WEST_COAST_SOUTH_AMERICA">West Coast South America</option>
            <option value="WEST_COAST_UNITED_STATES">West Coast United States</option>
            <option value="WEST_MEDITERRANEAN">West Mediterranean</option>
          </select>
        </div>

        <!--
        <div class="col-sm-6 col-lg-2 px-1 pb-2">
          <select name="category" class="brand-border" title="Yacht type">
            <option value="">Yacht Type</option>
            <option value="POWER">Motor</option>
            <option value="SAIL">Sailing</option>
          </select>
        </div>
        <div class="col-sm-6 col-lg-2 px-1 pb-2">
          <select name="guests" class="brand-border m-b-0" title="Guests">
            <option value="0">Guests</option>
            <option value="1">1 Person</option>
            <option value="2">2 People</option>
            <option value="3">3 People</option>
            <option value="4">4 People</option>
            <option value="5">5 People</option>
            <option value="6">6 People</option>
            <option value="7">7 People</option>
            <option value="8">8 People</option>
            <option value="9">9 People</option>
            <option value="10">10+ People</option>
          </select>
        </div>
        -->

        <!-- <div class="col-12 col col-lg-2 px-1 pb-2 pt-2 pt-lg-0">
          <input class="brand-bg brand-text" type="submit" value="Search" />
        </div> -->
      </div>
    </form>
  </div>
  <ul class="listings">
    <?php foreach ($yachts as $yacht) : ?>
      <li>
        <h3><a href="/apollo/listings/<?= $yacht->position ?>"><?= $yacht->name ?></a></h3>
        <a href="/apollo/listings/<?= $yacht->position ?>"><img src="<?= str_replace('https://images.charterindex.com/', '/assets/img_headers/', $yacht->header_image) ?>"></a><br>
        Length <?= $yacht->key_details->length ?><br>
        Guests <?= $yacht->key_details->sleeps ?>/<?= $yacht->key_details->cabins ?> Bedrooms<br>
        FROM <?= $yacht->key_details->price_from ?>
      </li>
    <?php endforeach; ?>
  </ul>

  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" crossorigin="anonymous"></script>
</body>

</html>
