<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Panagea - Premium site template for travel agencies, hotels and restaurant listing.">
  <meta name="author" content="Ansonika">
  <title>Panagea | Premium site template for travel agencies, hotels and restaurant listing.</title>

  <!-- Favicons-->
  <link rel="shortcut icon" href="img/favicon.ico" type="image/x-icon">
  <link rel="apple-touch-icon" type="image/x-icon" href="img/apple-touch-icon-57x57-precomposed.png">
  <link rel="apple-touch-icon" type="image/x-icon" sizes="72x72" href="img/apple-touch-icon-72x72-precomposed.png">
  <link rel="apple-touch-icon" type="image/x-icon" sizes="114x114" href="img/apple-touch-icon-114x114-precomposed.png">
  <link rel="apple-touch-icon" type="image/x-icon" sizes="144x144" href="img/apple-touch-icon-144x144-precomposed.png">

  <!-- GOOGLE WEB FONT -->
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">

  <!-- BASE CSS -->
  <link href="/assets/css/bootstrap.min.css" rel="stylesheet">
  <link href="/assets/css/style.css" rel="stylesheet">
  <link href="/assets/css/vendors.css" rel="stylesheet">

  <!-- YOUR CUSTOM CSS -->
  <link href="/assets/css/custom.css" rel="stylesheet">
</head>

<body>
  <div id="page">
    <include href="templates/header.phtml" />
    <main>
      <section class="hero_in tours">
        <div class="wrapper">
          <div class="container">
            <h1 class="fadeInUp"><span></span>Yacht Listings</h1>
          </div>
        </div>
      </section>
      <!--/hero_in-->

      <div class="filters_listing sticky_horizontal">
        <div class="container">
          <ul class="clearfix">
            <li>
              <div class="switch-field">
                <input type="radio" id="all" name="listing_filter" value="all" checked data-filter="*" class="selected">
                <label for="all">All</label>
                <input type="radio" id="popular" name="listing_filter" value="popular" data-filter=".popular">
                <label for="popular">Popular</label>
                <input type="radio" id="latest" name="listing_filter" value="latest" data-filter=".latest">
                <label for="latest">Latest</label>
              </div>
            </li>
            <li>
              <div class="layout_view">
                <a href="tours-grid-isotope.html"><i class="icon-th"></i></a>
                <a href="#0" class="active"><i class="icon-th-list"></i></a>
              </div>
            </li>
            <li>
              <a class="btn_map" data-toggle="collapse" href="#collapseMap" aria-expanded="false" aria-controls="collapseMap" data-text-swap="Hide map" data-text-original="View on map">View on map</a>
            </li>
          </ul>
        </div>
        <!-- /container -->
      </div>
      <!-- /filters -->

      <div class="collapse" id="collapseMap">
        <div id="map" class="map"></div>
      </div>
      <!-- End Map -->

      <div class="container margin_60_35">
        <div class="col-lg-12">
          <div class="row no-gutters custom-search-input-2 inner">
            <div class="col-lg-3">
              <select class="wide">
                <option>Location...</option>
                <repeat group="@locations" value="@location">
                  <option>{{ @location }}</option>
                </repeat>
              </select>
            </div>
            <div class="col-lg-3">
              <div class="form-group">
                <input class="form-control" type="text" placeholder="Dates">
                <i class="icon_pin_alt"></i>
              </div>
            </div>
            <div class="col-lg-3">
              <select class="wide">
                <option>All Yacht Types</option>
                <option>Sailboat</option>
                <option>Catamaran</option>
                <option>Houseboat</option>
                <option>Motorboat</option>
                <option>Motor yacht</option>
                <option>Power catamaran</option>
              </select>
            </div>
            <div class="col-lg-3">
              <input type="submit" class="btn_search" value="Search">
            </div>
          </div>
          <!-- /row -->
        </div>
        <!-- /custom-search-input-2 -->
        <div class="isotope-wrapper">
          <repeat group="{{ @listings }}" value="{{ @listing }}">
            <div class="box_list isotope-item latest popular">
              <div class="row no-gutters">
                <div class="col-lg-5">
                  <figure>
                    <small>{{ @listing.type }} yacht</small>
                    <a href="/listings/{{ @listing.id }}">
                      <img src="{{ @listing.header_image }}" class="img-fluid" alt="" width="800" height="533">
                      <div class="read_more"><span>Read more</span></div>
                    </a>
                  </figure>
                </div>
                <div class="col-lg-7">
                  <div class="wrapper">
                    <a href="#0" class="wish_bt"></a>
                    <h3><a href="/listings/{{ @listing.id }}">{{ @listing.name }}</a></h3>
                    <p class="wide">A big wide description to get around the masonary javascript layout. More sentences are needed. How many more sentences are needed, a few more.</p>
                    <!-- <p class="wide">Dicam diceret ut ius, no epicuri dissentiet philosophia vix. Id usu zril tacimates neglegentur. Eam id legimus torquatos cotidieque, usu decore percipitur definitiones ex, nihil utinam recusabo mel no.</p> -->
                    Length: {{ @listing.spec_length }}<br>
                    Builder: {{ @listing.spec_builder }}<br>
                    Year built: {{ @listing.spec_launched }}<br>
                    Cabins: {{ @listing.cabins }}<br>
                    <!-- <span class="price">From <strong></strong> per week</span> -->
                  </div>
                  <ul>
                    <li>
                      <!--<i class="icon_clock_alt"></i>&nbsp;--><span class="price"><strong>${{ number_format(@listing.price) }}</strong> per week</span>
                    </li>
                    <li>
                      <div class="score"><span>Superb<em>350 Reviews</em></span><strong>8.9</strong></div>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </repeat>
          <!-- /box_list -->
        </div>
        <!-- /isotope-wrapper -->

        <p class="text-center add_top_30">
          <a href="/listings" class="btn_1 rounded">Previous</a>
          <a href="/listings" class="btn_1 rounded">Next</a>
        </p>

      </div>
      <!-- /container -->
      <div class="bg_color_1">
        <div class="container margin_60_35">
          <div class="row">
            <div class="col-md-4">
              <a href="#0" class="boxed_list">
                <i class="pe-7s-help2"></i>
                <h4>Need Help? Contact us</h4>
                <p>Cum appareat maiestatis interpretaris et, et sit.</p>
              </a>
            </div>
            <div class="col-md-4">
              <a href="#0" class="boxed_list">
                <i class="pe-7s-wallet"></i>
                <h4>Payments and Refunds</h4>
                <p>Qui ea nemore eruditi, magna prima possit eu mei.</p>
              </a>
            </div>
            <div class="col-md-4">
              <a href="#0" class="boxed_list">
                <i class="pe-7s-note2"></i>
                <h4>Quality Standards</h4>
                <p>Hinc vituperata sed ut, pro laudem nonumes ex.</p>
              </a>
            </div>
          </div>
          <!-- /row -->
        </div>
        <!-- /container -->
      </div>
      <!-- /bg_color_1 -->
    </main>
    <!--/main-->

    <footer>
      <div class="container margin_60_35">
        <div class="row">
          <div class="col-lg-5 col-md-12 p-r-5">
            <p><img src="/assets/img/logo.svg" width="150" height="36" alt=""></p>
            <p>Mea nibh meis philosophia eu. Duis legimus efficiantur ea sea. Id placerat tacimates definitionem sea, prima quidam vim no. Duo nobis persecuti cu. Nihil facilisi indoctum an vix, ut delectus expetendis vis.</p>
            <div class="follow_us">
              <ul>
                <li>Follow us</li>
                <li><a href="#0"><i class="ti-facebook"></i></a></li>
                <li><a href="#0"><i class="ti-twitter-alt"></i></a></li>
                <li><a href="#0"><i class="ti-google"></i></a></li>
                <li><a href="#0"><i class="ti-pinterest"></i></a></li>
                <li><a href="#0"><i class="ti-instagram"></i></a></li>
              </ul>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 ml-lg-auto">
            <h5>Useful links</h5>
            <ul class="links">
              <li><a href="about.html">About</a></li>
              <li><a href="login.html">Login</a></li>
              <li><a href="register.html">Register</a></li>
              <li><a href="blog.html">News &amp; Events</a></li>
              <li><a href="contacts.html">Contacts</a></li>
            </ul>
          </div>
          <div class="col-lg-3 col-md-6">
            <h5>Contact with Us</h5>
            <ul class="contacts">
              <li><a href="tel://61280932400"><i class="ti-mobile"></i> + 61 23 8093 3400</a></li>
              <li><a href="mailto:info@Panagea.com"><i class="ti-email"></i> info@Panagea.com</a></li>
            </ul>
            <div id="newsletter">
              <h6>Newsletter</h6>
              <div id="message-newsletter"></div>
              <form method="post" action="assets/newsletter.php" name="newsletter_form" id="newsletter_form">
                <div class="form-group">
                  <input type="email" name="email_newsletter" id="email_newsletter" class="form-control" placeholder="Your email">
                  <input type="submit" value="Submit" id="submit-newsletter">
                </div>
              </form>
            </div>
          </div>
        </div>
        <!--/row-->
        <hr>
        <div class="row">
          <div class="col-lg-6">
            <ul id="footer-selector">
              <li>
                <div class="styled-select" id="lang-selector">
                  <select>
                    <option value="English" selected>English</option>
                    <option value="French">French</option>
                    <option value="Spanish">Spanish</option>
                    <option value="Russian">Russian</option>
                  </select>
                </div>
              </li>
              <li>
                <div class="styled-select" id="currency-selector">
                  <select>
                    <option value="US Dollars" selected>US Dollars</option>
                    <option value="Euro">Euro</option>
                  </select>
                </div>
              </li>
              <li><img src="/assets/img/cards_all.svg" alt=""></li>
            </ul>
          </div>
          <div class="col-lg-6">
            <ul id="additional_links">
              <li><a href="#0">Terms and conditions</a></li>
              <li><a href="#0">Privacy</a></li>
              <li><span>© 2022 CharterBoats.com</span></li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
    <!--/footer-->
  </div>
  <!-- page -->

  <!-- Sign In Popup -->
  <div id="sign-in-dialog" class="zoom-anim-dialog mfp-hide">
    <div class="small-dialog-header">
      <h3>Sign In</h3>
    </div>
    <form>
      <div class="sign-in-wrapper">
        <a href="#0" class="social_bt facebook">Login with Facebook</a>
        <a href="#0" class="social_bt google">Login with Google</a>
        <div class="divider"><span>Or</span></div>
        <div class="form-group">
          <label>Email</label>
          <input type="email" class="form-control" name="email" id="email">
          <i class="icon_mail_alt"></i>
        </div>
        <div class="form-group">
          <label>Password</label>
          <input type="password" class="form-control" name="password" id="password" value="">
          <i class="icon_lock_alt"></i>
        </div>
        <div class="clearfix add_bottom_15">
          <div class="checkboxes float-left">
            <label class="container_check">Remember me
              <input type="checkbox">
              <span class="checkmark"></span>
            </label>
          </div>
          <div class="float-right mt-1"><a id="forgot" href="javascript:void(0);">Forgot Password?</a></div>
        </div>
        <div class="text-center"><input type="submit" value="Log In" class="btn_1 full-width"></div>
        <div class="text-center">
          Don’t have an account? <a href="register.html">Sign up</a>
        </div>
        <div id="forgot_pw">
          <div class="form-group">
            <label>Please confirm login email below</label>
            <input type="email" class="form-control" name="email_forgot" id="email_forgot">
            <i class="icon_mail_alt"></i>
          </div>
          <p>You will receive an email containing a link allowing you to reset your password to a new preferred one.</p>
          <div class="text-center"><input type="submit" value="Reset Password" class="btn_1"></div>
        </div>
      </div>
    </form>
    <!--form -->
  </div>
  <!-- /Sign In Popup -->

  <div id="toTop"></div><!-- Back to top button -->

  <!-- COMMON SCRIPTS -->
  <script src="/assets/js/common_scripts.js"></script>
  <script src="/assets/js/main.js"></script>
  <script src="/assets/js/validate.js"></script>

  <!-- Map -->
  <script src="http://maps.googleapis.com/maps/api/js"></script>
  <script src="/assets/js/markerclusterer.js"></script>
  <script src="/assets/js/map_tours.js"></script>
  <script src="/assets/js/infobox.js"></script>

  <!-- Masonry Filtering -->
  <script src="/assets/js/isotope.min.js"></script>
  <script>
    $(window).on('load', function() {
      var $container = $('.isotope-wrapper');
      $container.isotope({
        itemSelector: '.isotope-item',
        layoutMode: 'masonry'
      });
    });
    $('.filters_listing').on('click', 'input', 'change', function() {
      var selector = $(this).attr('data-filter');
      $('.isotope-wrapper').isotope({
        filter: selector
      });
    });
  </script>
</body>

</html>
